services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    restart: always

  service:
    build:
      context: .
      target: development
    ports:
      - 8085:8085
    links:
      - "localstack:localstack"
      - "mongodb:mongodb"
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    profiles:
      - service
    env_file:
      - "compose/aws.env"
      - "compose/secrets.env"
    environment:
      PORT: ${PORT:-8085}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL:-http://localstack:4566}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
    develop:
      watch:
        - action: sync
          path: ./app
          target: /home/nonroot/app
          ignore:
            - README.md
            - "**/*.md"
            - "**/test_*.py"
            - tests/**/*
            - .git/**/*
            - .venv/**/*
            - .pytest_cache/**/*
            - .ruff_cache/**/*
            - .vscode/**/*
            - .github/**/*
            - requirements-dev.txt
            - pytest.ini
            - .pre-commit-config.yaml
            - sonar-project.properties
            - LICENCE
        - action: rebuild
          path: ./pyproject.toml
          target: /home/nonroot/pyproject.toml
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
