services:
  mongodb:
    container_name: mongodb
    networks:
      - cdp-network
    image: mongo:6.0.13
    ports:
      - 27017:27017
    volumes:
      - ./ssl:/etc/ssl:ro
    command: [
      "--tlsMode", "requireTLS",
      "--tlsCertificateKeyFile", "etc/ssl/mongodb.pem"
    ]
  service:
    #build:
    #  context: ../..
    image: cdp-python-backend-template
    container_name: cdp-python-backend-template
    networks:
      - cdp-network
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      PORT: 8085
      MONGO_URI: "mongodb://mongodb:27017/?tls=true"
      TRUSTSTORE_CDP: ${MONGODB_TEST_CA_PEM}
    healthcheck:
      test: curl http://localhost:8085/health
      start_period: 1s
      interval: 2s

networks:
  cdp-network:
    driver: bridge
