name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: |
          pipx install uv
          uv sync --frozen
          uv run ruff check
          uv run pytest

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag cdp-python-backend-template .
          exit $?

#      - name: SonarCloud Scan
#        if: github.actor != 'dependabot[bot]'
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
